version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/mignonnesaurus-blog
    steps:
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pipenv
            pipenv install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            pipenv run coverage run manage.py test tests -v 2
            pipenv run coverage xml
            ./cc-test-reporter after-build --debug --coverage-input-type coverage.py --exit-code $?
      - store_artifacts:
          path: htmlcov
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku (Staging)
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
