version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.5.1
  qlty-orb: qltysh/qlty-orb@0.0
jobs:
  test:
    docker:
      - image: cimg/python:3.12.11-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/mignonnesaurus-blog
    steps:
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pipenv
            pipenv install

      - run:
          name: Run tests
          command: |
            pipenv run coverage run manage.py test tests -v 2
            pipenv run coverage xml
      - qlty-orb/coverage_publish:
          files: coverage.xml
workflows:
  version: 2
  test:
    jobs:
      - test
